#设置端口
server:
  port: 8088
#配置数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  application:
    name: springboot-mybatis
#配置mybatis-plus
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mapper/*Dao.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
#  level.root: warn  #日志级别设置
#  file:
#    path: D:\IdeaProject\log\springboot-mybatis    #日志文件路径
#  config: classpath:logback-config.xml
  config: classpath:logback-spring-backup.xml    #配置完整能看懂
#  level.*: info

